# use Ganache's forked mainnet mode as the default network
networks:
  default: development

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.7.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7"