# Use Ganache's forked mainnet mode as the default network
networks:
  default: development

# Require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7

# Path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.7.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7"

# Property-based tests run 10 times with random inputs rather than the default 50
hypothesis:
  max_examples: 10
