# Use Ganache's network as the default
networks:
  default: development

# Require OpenZeppelin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

compiler:
  evm_version: "london"
  solc:
    optimizer:
      enabled: true
      runs: 800
    version: 0.8.20

hypothesis:
  max_examples: 50
