# Use Ganache's network as the default
networks:
  default: development

compiler:
  evm_version: "paris"
  solc:
    optimizer:
      enabled: true
      runs: 800
    version: 0.8.20

hypothesis:
  max_examples: 50
