kind: pipeline
name: chainflip-eth-contracts
type: docker

clone:
  disable: true

workspace:
  path: /home/circleci

steps:
  - name: test
    image: ghcr.io/chainflip-io/eth-brownie:latest
    commands:
      - git clone https://github.com/chainflip-io/chainflip-eth-contracts.git
      - cd chainflip-eth-contracts
      - export PATH="$(yarn global bin):$PATH"
      - yarn global add ganache-cli
      - poetry install
      - poetry update eth-brownie
      - brownie pm install OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7
      - poetry run brownie test --stateful false

trigger:
  event:
    - pull_request

image_pull_secrets:
  - dockerconfigjson
