kind: pipeline
name: chainflip-eth-contracts
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie
      dockerfile: Dockerfile.eth-brownie
      registry: ghcr.io
      tags: latest
      cache_from: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest

  - name: test
    pull: always
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest
    commands:
      - which poetry
      - /home/circleci/.poetry/bin/poetry install
      - brownie pm install OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7
      - /home/circleci/.poetry/bin/poetry run brownie test --stateful false

trigger:
  event:
    - pull_request

image_pull_secrets:
  - dockerconfigjson
