kind: pipeline
name: chainflip-eth-contracts
type: docker

clone:
  disable: true

workspace:
  path: ~/

steps:
  - name: test
    image: ghcr.io/chainflip-io/eth-brownie:latest
    commands:
      - pwd
      - whoami
      - ls
      - git clone https://github.com/chainflip-io/chainflip-eth-contracts.git
      - cd chainflip-eth-contracts
      - poetry shell
      - poetry install
      - brownie pm install OpenZeppelin/openzeppelin-contracts@3.3.0-solc-0.7
      - brownie test
trigger:
  event:
    - pull_request
image_pull_secrets:
  - dockerconfigjson
