kind: pipeline
name: chainflip-eth-contracts
type: docker

#clone:
#  disable: false

workspace:
  path: /home/circleci

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie
      dockerfile: Dockerfile.eth-brownie
      registry: ghcr.io
      tags: latest
      cache_from: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest

  - name: test
    pull: always
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest
    commands:
      - poetry run brownie test --stateful false

trigger:
  event:
    - pull_request

image_pull_secrets:
  - dockerconfigjson
