on:
  workflow_call:
    inputs:
      stateful:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 360

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - run: npm install
    - run: echo /root/.local/bin >> $GITHUB_PATH
    - run: poetry install --quiet
    - run: poetry run brownie test tests/stateful/test_all.py --network hardhat --stateful ${{inputs.stateful}}

  test0:
    runs-on: self-hosted
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - run: npm install
    - run: echo /root/.local/bin >> $GITHUB_PATH
    - run: poetry install --quiet
    - run: poetry run brownie test tests/stateful/test_all.py --network hardhat --stateful ${{inputs.stateful}} --hypothesis-seed 0


  test1:
    runs-on: self-hosted
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - run: npm install
    - run: echo /root/.local/bin >> $GITHUB_PATH
    - run: poetry install --quiet
    # For dev purposes
    - run: poetry run brownie test tests/stateful/test_all.py --network hardhat --stateful ${{inputs.stateful}} --hypothesis-seed 1

  test2:
    runs-on: self-hosted
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - run: npm install
    - run: echo /root/.local/bin >> $GITHUB_PATH
    - run: poetry install --quiet
    # For dev purposes
    - run: poetry run brownie test tests/stateful/test_all.py --network hardhat --stateful ${{inputs.stateful}} --hypothesis-seed 2

  # test3:
  #   runs-on: self-hosted
  #   timeout-minutes: ${{ inputs.timeout_minutes }}
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '14'
  #       cache: npm
  #   - run: npm install
  #   - run: echo /root/.local/bin >> $GITHUB_PATH
  #   - run: poetry install --quiet
  #   # For dev purposes
  #   - run: poetry run brownie test tests/stateful/test_all.py --network hardhat --stateful ${{inputs.stateful}} --hypothesis-seed 3