name: Fuzzer Testing
on: push

jobs:
  # lint:
  #   # Skipping it for now because it needs to be updated with the new fuzzing tests
  #   if: false

  #   uses: ./.github/workflows/.lint.yml

  fuzzer-tests:
    name: Fuzzer
    # needs: lint
    runs-on: [self-hosted, linux, x64, ephemeral]
    timeout-minutes: 30
    # strategy:
    #   matrix:
    #     contract: [TestEchidna, TestEchidnaGovComm]
    #     config: [echidna-assertion, echidna-property]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # - name: Install Poetry
      #   uses: snok/install-poetry@v1

      - run: npm install --global ganache-cli
      - run: npm install --global yarn
      - run: yarn
      - run: pip3 install crytic-compile

      - run: |
          echo Y | sudo apt-get install software-properties-common
      - run: sudo apt-get update
      - run: sudo add-apt-repository ppa:ethereum/ethereum
      - run: |
          echo Y | sudo apt-get install solc
      - run: pip3 install slither-analyzer
      # - run: poetry install
      # - run: poetry run brownie pm install OpenZeppelin/openzeppelin-contracts@4.8.3

      - run: |
          echo Y | sudo apt-get install build-essential procps curl file git
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/ubuntu/.profile
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - run: |
          echo Y | sudo apt-get install build-essential
      - run: /home/linuxbrew/.linuxbrew/bin/brew install gcc
      - run: /home/linuxbrew/.linuxbrew/bin/brew help
      - run: /home/linuxbrew/.linuxbrew/bin/brew install echidna

      - run: slither --version
      - run: crytic-compile --version
      - run: solc-select use 0.8.20
      # - run: solc --version

      - run: /home/linuxbrew/.linuxbrew/bin/echidna contracts/echidna/tests/NewTestEchidna.sol --contract NewTestEchidna --config contracts/echidna/tests/echidna-assertion.config.yml

      # - run: curl -fL https://github.com/crytic/echidna/releases/download/v2.2.0/echidna-2.2.0-Ubuntu-22.04.tar.gz -o echidna-2.2.0-Ubuntu-22.04.tar.gz
      # - run: tar -xvf echidna-2.2.0-Ubuntu-22.04.tar.gz

      # Running actual fuzzing tests
      # - run: poetry run ./echidna contracts/echidna/tests/${{ matrix.contract }}.sol --contract ${{ matrix.contract }} --config contracts/echidna/tests/${{ matrix.config }}.config.yml
      # - run: poetry run ./echidna contracts/echidna/tests/${{ matrix.contract }}.sol --contract ${{ matrix.contract }} --config contracts/echidna/tests/${{ matrix.config }}.config.yml
