name: Release

on: push

jobs:
  release:
    runs-on: [self-hosted, linux, x64, ephemeral]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python virtualenv
        run: pip install virtualenv

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install zip
        run: |
          sudo apt update
          sudo apt install zip

      - run: npm install --global ganache-cli
      - run: npm install --global yarn
      - run: yarn
      - run: poetry install

      # Ensure that the Deposit's bytecode hasn't changed
      - run: poetry run brownie test tests/unit/vault/test_deployAndFetchBatch.py::test_getCreate2Addr --network hardhat

      - name: Zip ABIs
        run: |
          cat ./build/contracts/Deposit.json
