name: Stateful Tests
on: push

jobs:
  lint:
    name: Linting
    uses: chainflip-io/chainflip-eth-contracts/.github/workflows/.lint.yaml@master

  stateful-tests:
    name: Stateful Tests
    needs: lint
    uses: chainflip-io/chainflip-eth-contracts/.github/workflows/.test.yaml@test/add-stateful-govWithraw
    with:
      stateful: true
      timeout_minutes: 3600
