name: Stateless Tests
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  stateless-tests:
    name: Stateless Tests
    runs-on: [self-hosted, linux, x64, ephemeral]
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python virtualenv
        run: pip install virtualenv

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: npm install --global yarn
      - run: npm install --global ganache-cli
      - run: yarn
      - run: poetry install
      # - run: poetry run brownie pm intall OpenZeppelin/openzeppelin-contracts@4.0.0
      # - run: sudo snap install solc --edge
      - run: poetry run brownie compile
      - run: echo "$(cat ./build/contracts/Deposit.json | jq .bytecode)"
      - run: echo "$(cat ./build/contracts/Deposit.json | jq .bytecode)" | sha256sum
      - run: solc --version

      - run: poetry run brownie test tests/unit/vault/test_deployAndFetchBatch.py::test_getCreate2Addr --network hardhat --stateful false
