name: Stateful Test
on: 
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-tests:
    name: Stateful Tests
    uses: chainflip-io/chainflip-eth-contracts/.github/workflows/.test.yaml@master
    with:
      stateful: true
      runs_on: self-hosted
